version: "3.9"

services:
  frontend:
    build: ./frontend
    container_name: express-service
    restart: always
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: flask-service
    restart: always
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx-service
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
